### ISSUE TITLE
replacing PyTorch Cuda with tensor flow for MacOS

### ISSUE THREAD

**Issue by MugdhaSathe** [royerlab/ultrack#103]
Hi, 
I am encountering issues with trying to run the code in my iMac Machine which is not compatible with PyTorch cuda. I was wondering if you have a version to use with tensor flow for Mac or replace the gpu part with cpu. 
please let me know if you need any further information.

Thanks,
Mugdha

**Comment by JoOkuma** [comment]
Hi @MugdhaSathe,

Cupy is not a hard requirement, you can use `ultrack` with just numpy.
We don't plan to support TensorFlow.
