### ISSUE TITLE
Application to 3D images of mouse brain

### ISSUE THREAD

**Issue by GiangTranHU** [royerlab/ultrack#120]
I am new to use ultrack, may I ask a question about it?
May ultrack be used to detect cells in 3D images of mouse brain?
Thank you very much!

**Comment by GiangTranHU** [comment]
Hi JoOkuma,
Thank you very much for your help!
I work with fixed tissue, I will try with detect_foreground from your program.
I also see you applied SAM in your program, may you please give me advice if SAM is useful for my case, especially in 3D images of cells?

**Comment by GiangTranHU** [comment]
Thank JoOkuma for help!
May I ask a question about cellpose?
Does cellpose need to re-train the model before using?

**Comment by JoOkuma** [comment]
@GiangTranHU, most of the time, we don't need to re-train for 2D images. For 3D, we usually fine-tune (re-train) our models, but then you need to annotate some data :(.

Others might have had a different experience. The [imageSC forum](https://forum.image.sc) could provide additional info.

**Comment by GiangTranHU** [comment]
Thank JoOkuma!
