### ISSUE TITLE
Update installation instructions on Github

### ISSUE THREAD

**Issue by bentaculum** [royerlab/ultrack#151]
Hi Jordao, just noticed a small convenience thing, the install instructions with more conda deps from the [docs](https://royerlab.github.io/ultrack/install.html) are needed e.g. for a MacOS install. The instructions in the [README.md](README.md#installation) lead to dep problem with `higra`.

**Comment by JoOkuma** [comment]
Thanks @bentaculum , I'm updating the README on #152
