### ISSUE TITLE
NameError: name 'detection' is not define

### ISSUE THREAD

**Issue by jazberna1** [royerlab/ultrack#157]
Hello,

I have encountered the following error when running the following line 
`trajectory = advenct_from_quasi_random(flow, detection.shape[-3:], n_samples=1000)`
in the `tribolium_cartograph.ipynb` notebook

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[11], line 1
----> 1 trajectory = advenct_from_quasi_random(flow, detection.shape[-3:], n_samples=1000)
      2 flow_tracklets = pd.DataFrame(
      3     trajectories_to_tracks(trajectory),
      4     columns=["track_id", "t", "z", "y", "x"],
      5 )
      6 flow_tracklets[["z", "y", "x"]] += 0.5  # napari was crashing otherwise, might be an openGL issue

NameError: name 'detection' is not defined
```

I have been able to run the notebook up to that point. From the notebook code I see the` detection` object does not appear anywhere above in the code.

Any help to get the notebook running will be much appreciated.

Thanks
Jorge

**Comment by JoOkuma** [comment]
Hi @jazberna1, are you executing it in order? This variable was created on the previous chunks.

**Comment by jazberna1** [comment]
Hello @JoOkuma ,

Sorry, my bad. I must have tried to run on a expired session. I see the detection variable created on the previous chunks.

closing this one.

Thanks so much!!
Jorge
