### ISSUE TITLE
not able to add multiple segmentation layers to  'Auto detect contours from labels' workflow in the Napari plugin

### ISSUE THREAD

**Issue by jazberna1** [royerlab/ultrack#162]
Hello,

If I understood well from the publication, Ultrack is able to track cells by combining multiple segmenation inputs. That's is precisely what I am trying to do using the 'Auto detect contours from labels' workflow in the Napari plugin.  However from the 'labels' dropdown menu I can only select a single layer (see screenshot). It is possible that this has not been implemented in the Napari plugin?

![IMG20241107113538](https://github.com/user-attachments/assets/fbd5862e-860e-4973-bd2f-dcf059d0c7b5)

Thanks
Jorge

**Comment by JoOkuma** [comment]
Hi @jazberna1,

This will detect individual contours, to combine them, you can do it manually using napari.

```python
contour_1 = viewer.layers[<YOUR CONTOUR>].data
contour_2 = viewer.layers[<YOUR OTHER CONTOUR>].data
viewer.add_image((contour_1 + contour_2) / 2, name="combined contour")

foreground_1 = viewer.layers[<FOREGROUND>].data
foreground_2 = viewer.layers[<OTHER FOREGROUND>].data
viewer.add_image(np.logical_or(foreground_1, foreground_2), name="combined foreground")
```

does this solve your problem?

best,
Jordao

**Comment by JoOkuma** [comment]
@jazberna1, yes, you got it right!
