### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by haesleinhuepf** [royerlab/ultrack#44]
Hi all,

what an awesome library! Would it be possible to create a release, e.g. on pypi? That would be great for reproducible research. It enables people to run and compare specific versions of the code.

Thanks!

Best,
Robert

**Comment by JoOkuma** [comment]
@haesleinhuepf, my bad. I tagged this commit and uploaded it to pypi.
Thanks for pointing this out.

**Comment by haesleinhuepf** [comment]
Awesome thanks 🎉
