### ISSUE TITLE
Getting in touch

### ISSUE THREAD

**Issue by tischi** [royerlab/ultrack#48]
Hi, I would love to discuss the applicability of your tracking code to one of our datasets. Is there a chance to get in touch?

**Comment by JoOkuma** [comment]
Hey @tischi, I'm happy to help. 

I've "office hours" slots [here](https://calendly.com/jbragantini/office-hours).
If that doesn't work, drop me an email (`jordao.bragantini at czbiohub dot org`) with your availability.

We can leave this issue open. I think it might be helpful for others :).

**Comment by tischi** [comment]
We got in touch ❤️
