### ISSUE TITLE
Reproducing 2d stardist example conda env

### ISSUE THREAD

**Issue by folterj** [royerlab/ultrack#55]
Trying to create the GPU conda env from the stardist_2d example provided I get:
(OS: Windows 10 64-bit, CUDA 12.3)

```
ResolvePackageNotFound:
  - rapidsai::cucim
  - coin-or-cbc
  - conda-forge::tensorflow-gpu=2.11.0
```

**Comment by JoOkuma** [comment]
Hi @folterj, thanks for raising this issue.

I don't have a Windows machine to test this, so I can't provide a direct solution.
However, we can tweak the dependencies.

I recommend:
- removing `cucim` and `cupy` from the environment file (they are not a hard requirement).
- removing `coin-or-cbc` and making sure you have gurobi license, you can get a [free academic license](https://www.gurobi.com/features/academic-wls-license/).
- loosening the tensorflow dependency.

Note that some operational systems have issues installing TensorFlow and torch (track dependency), so a different example might be easier to run.

**Comment by JoOkuma** [comment]
Hi @folterj,

Gurobi has really helpful resources, [this one](https://support.gurobi.com/hc/en-us/articles/4534601245713-How-do-I-get-started-with-Gurobi-for-academic-users-) might help you out.

If you're in a non-academic institution, you could try installing the other solver without conda; their instructions [is here](https://github.com/coin-or/Cbc).

Note that CBC is much slower than gurobi.

Cheers,

**Comment by folterj** [comment]
Thank you, I was able to configure this now and set up the license etc.
Perhaps some more detail on this could be added to the example/readme?
