### ISSUE TITLE
CLI export compatiblity with napari tracks reader plugin

### ISSUE THREAD

**Issue by jackyko1991** [royerlab/ultrack#58]
`ultrack export zarr-napari ` not natively compatible with [napari tracks reader plugin](https://www.napari-hub.org/plugins/napari-tracks-reader)

CSV header has to be in name `TrackID`, `t`, `x`, `y`, `z`. Note that the header order does not matter. Currently need to manually modify the output file. Perhaps adding an option to fit the header name.

Or should I change to use TrackMate output?

**Comment by JoOkuma** [comment]
Hi @jackyko1991,

Ultrack should come with its own napari reader plugin.
It's very similar to the plugin you linked, but it also loads other columns and the division relationship.

Is the ultrack reader plugin not available for you?
Could you try checking if there were any errors by going to the `Plugins ... > Plugins Errors` in the menu bar?

**Comment by jackyko1991** [comment]
Hi Jordao,

Do you mean I need to use napari comes with ultrack but not the native one? Would the plugins be available to install separately?

Jacky
________________________________

**Comment by JoOkuma** [comment]
The ultrack **.csv** reader comes with the ultrack python package.
They're implemented [here](https://github.com/royerlab/ultrack/blob/main/ultrack/napari.yaml) and [here](https://github.com/royerlab/ultrack/blob/main/ultrack/reader/napari_reader.py) and it should be enabled by default.

Would it be better to have it as a separate plugin? I can see how ultrack has several dependencies, and it might not be the most straightforward package to install.

**Comment by jackyko1991** [comment]
I am working on Napari on a machine with native Napari only. 

IMO I don't think a separate plugin is necessary. I may check with the author of [napari tracks reader plugin](https://www.napari-hub.org/plugins/napari-tracks-reader) to add the function to load custom header names.

**Comment by JoOkuma** [comment]
recently, we update so ultrack provides its own napari-reader plugin
