### ISSUE TITLE
Correct for jittering

### ISSUE THREAD

**Issue by brunicardoso** [royerlab/ultrack#78]
I am not sure if Ultrack has a function to correct for jittering? In may dataset, when there is a little jitter (usually occurs in the first to the second frame and when a treatment is added), the tracks are messed up.

**Comment by JoOkuma** [comment]
Hi, Alexandre

We have a more sophisticated and (brittle) approach to register different frames using a flow field; it's used on [this example](https://github.com/royerlab/ultrack/blob/main/examples/flow_field_3d/tribolium_cartograph.ipynb).

If your jitter is mostly a translation shift, using `skimage` to register when pre-processing your image will be more robust.

This function is a good starting point:
```python
import numpy as np
import scipy.ndimage as ndi
from skimage.registration import phase_cross_correlation
from tqdm import tqdm

def _register(video: np.ndarray) -> np.ndarray:
    # registration using channel 1
    reg_channel = 1
    for t in tqdm(range(video.shape[0] - 1), "register"):
        shift, error, _ = phase_cross_correlation(
            video[t, reg_channel],
            video[t + 1, reg_channel],
            normalization=None,
            overlap_ratio=0.25,
        )
        video[t+1] = ndi.shift(video[t+1], (0, *shift), order=1)
    return video
```

**Comment by brunicardoso** [comment]
Thank, Jordao! I will try it

**Comment by JoOkuma** [comment]
We included [register_timelapse](https://github.com/royerlab/ultrack/blob/09ed622ff53f17264a4c309095ce32450a7028f3/ultrack/imgproc/register.py#L16) to do this, @brunicardoso . I'm closing this issue. Thanks for the request.
