### ISSUE TITLE
tracking parameters related to the weighting of the raw intensity values

### ISSUE THREAD

**Issue by gouthamr321** [royerlab/ultrack#95]
Hello,

Very cool work!

When running the tracking (after we already have segmentations), I see that we are passing in the raw images themselves to the track function in ultrack/core/main.py. I understand that that is because the florescence intensity is used for the linking steps. But for cases where we are tracking nuclei from brightfield, where the raw images don't have as meaningful intensity gradients, Is there a way to change the weight of the importance of the raw intensity values that are extracted for the ILP? Some specific parameter in the tracking_config schema perhaps?

Thanks!

**Comment by JoOkuma** [comment]
Hey @gouthamr321,

We only use fluorescence information for tracking if you provide the `images` parameter of the `track` function.
Otherwise, we use the cells' segments mask to compute the association between segments.

```python3
def track(
    config: MainConfig,
    *,
    labels,
    sigma,
    detection,
    edges,
    images,   # <- don't use this in your case.
    scale,
    vector_field,
    overwrite,
):
```

Feel free to drop other questions :)

**Comment by JoOkuma** [comment]
Glad to hear @gouthamr321! I'll close the issue.
